main page visual part end i think??
h3770k1k1/restaurant-site pull request #3
Opened 2023-03-24 21:07 UTC by h3770k1k1

2023-03-27 19:12 UTC, kamil-ciesla requested changes

2023-03-27 19:12 UTC, kamil-ciesla commented on src/App.js
> +		<Suspense fallback="Loading...">
na pewno chcesz cały main container oblec w ten Suspense? nie wystarczy oblec tylko elementów z translacjami?

2023-03-27 19:12 UTC, kamil-ciesla commented on src/components/Contact.js
> +	return <div>anhgtyknejej</div>;
chyba nie rozumiem koncepcji, wyjaśnisz do czego potrzebny ci komponent Careers, oraz czemu jest w pliku Contact?

2023-03-27 19:12 UTC, kamil-ciesla commented on src/components/Footer.js
> +					<img className="up-arrow-icon " src={UpArrowIcon} />
myślę że wersja bez spacji była lepsza :P

2023-03-27 19:12 UTC, kamil-ciesla commented on src/App.js
> +
tej linijki chyba nie potrzeba

2023-03-27 19:12 UTC, kamil-ciesla commented on src/App.js
> +	.use(initReactI18next)
nie lepiej to złączyć z poprzednią linijką? i18n i tak jest krótkie

2023-03-27 19:12 UTC, kamil-ciesla commented on src/components/Footer.js
>  		if (currentScrollTop > prevScrollTop) {
dlaczego dodajesz logike w środku renderowania komponentu?

2023-03-27 19:12 UTC, kamil-ciesla commented on src/components/Footer.js
> +			showButton();
czy wiesz w jakim momencie (i jak często) ta funkcja będzie wywoływana?

2023-03-27 19:12 UTC, kamil-ciesla commented on src/components/Footer.js
> +	console.log("gonwo");
💩

2023-03-27 19:12 UTC, kamil-ciesla commented on src/components/Navbar.js
> +					</select>
elementy w środku są różnego rodzaju, mimo że mają te samą funkcje  raz jest <a>, innym razem option, posiadają równiez różne klasy, i język polski nie posiada value

2023-03-27 19:12 UTC, kamil-ciesla commented on src/index.js
> +});
czy na pewno powinno być to definiowane w pliku index.js?

2023-03-27 19:12 UTC, kamil-ciesla commented on src/resources/main-photo.png
both are awesome 🤤

2023-03-28 04:49 UTC, h3770k1k1 commented on src/components/Contact.js
> +	return <div>anhgtyknejej</div>;
> chyba nie rozumiem koncepcji, wyjaśnisz do czego potrzebny ci komponent Careers, oraz czemu jest w pliku Contact?

To pozostałość po tym jak próbowałam zrobić przeklikiwanie na podstronę contact. Patrzyłam sobie na przykładowy kod i zamiast Contact napisałam careers bo się zagapilam

2023-03-28 04:50 UTC, h3770k1k1 commented on src/components/Footer.js
> +					<img className="up-arrow-icon " src={UpArrowIcon} />
> myślę że wersja bez spacji była lepsza :P

Niewiem czy ta druga linijka w ogóle powinna tam byc

2023-03-28 04:51 UTC, h3770k1k1 commented on src/App.js
> +	.use(initReactI18next)
Nwm wszędzie w taki sposób to pisali

2023-03-28 04:55 UTC, h3770k1k1 commented on src/components/Navbar.js
> +					</select>
Powinnam dodać klasę language-option do angielskiego, a klasa choosen- language powinna zmieniać tylko kolor diva.
 Wiem że polski jeszcze niema value, trzeba dodać

2023-03-28 04:56 UTC, h3770k1k1 commented on src/index.js
> +});
To dotyczy app.js wiec pewnie tam?? Albo w jeszcze innym pliku?


> czy na pewno powinno być to definiowane w pliku index.js?

2023-03-28 04:56 UTC, h3770k1k1 commented on src/resources/main-photo.png
Thx

2023-03-28 04:56 UTC, h3770k1k1 commented on src/components/Footer.js
> +	console.log("gonwo");
> 💩

Nieprawda

2023-03-28 04:57 UTC, h3770k1k1 commented on src/components/Footer.js
> +			showButton();
> czy wiesz w jakim momencie (i jak często) ta funkcja będzie wywoływana?

Jeśli tylko trochę przeskroluje strone

2023-03-28 04:58 UTC, h3770k1k1 commented on src/components/Footer.js
> +			showButton();
> czy wiesz w jakim momencie (i jak często) ta funkcja będzie wywoływana?

Kiedy ruszę scrollem do dołu

2023-03-28 16:08 UTC, kamil-ciesla commented on src/components/Contact.js
> +	return <div>anhgtyknejej</div>;
to w takim razie usuń jak jest niepotrzebne

2023-03-28 16:10 UTC, kamil-ciesla commented on src/App.js
> +	.use(initReactI18next)
alright fine

2023-03-28 16:12 UTC, kamil-ciesla commented on src/index.js
> +});
myśle że to mogłoby być w oddzielnym pliku translations, i w App.js byłoby tylko inicjowane funkcją

2023-04-02 21:00 UTC, kamil-ciesla approved these changes
remove unneccesary translations files and console logs

2023-04-03 13:20 UTC, merged